export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_NEW_MARK_NAME = 'SET_NEW_MARK_NAME';
export const ADD_NEW_MARK = 'ADD_NEW_MARK';
export const ADD_NEW_POLYLINE_GEOMETRY = 'ADD_NEW_POLYLINE_GEOMETRY';
export const CLEAN_ADD_MARK_INPUT = 'CLEAN_ADD_MARK_INPUT';